### ISSUE TITLE
Vscode extension

### ISSUE THREAD

**Issue by oscartbeaumont** [oscartbeaumont/rspc#11]
Shortcuts for creating a router and quickly adding an operation to the existing router.

**Comment by kkharji** [comment]
> Shortcuts for creating a router and quickly adding an operation to the existing router.

I can pick this up, I just recently developed an extension. But you need to provide more details regarding the features and further explain the above.

**Comment by oscartbeaumont** [comment]
I was thinking of an extension with some built-in snippets such as creating a new file with a router or adding a new query/mutation/subscription/middleware to an existing router. This was really just a thought, I have no idea if it is actually going to be a good idea in practice.

The main goal of the extension would be to help users not have to remember syntax which intellisense can't help with and also to make it faster to do common things.

I am also now using both Neovim and Vscode so I would probably want support for both in the long run although these would probably end up being different things.
