### ISSUE TITLE
addSubscription TS signature is incorrect

### ISSUE THREAD

**Issue by campbellcole** [oscartbeaumont/rspc#186]
The signature for the `client.addSubscription` function cause valid parameters to error out, and causes "valid" parameters to throw runtime errors.

Given the following subscription in the `Router`:
```rs
router
    .subscription("logs", |s| {
        s(|_, test: ()| LogExportLayer::add_client())
    });
```

the following TS will throw a TypeScript error:
```ts
client.addSubscription(["logs"], { ... });
// Argument of type '["logs"]' is not assignable to parameter of type '["logs", []]'.
```

and if the `()` type is replaced with, say, `String`:
`Argument of type '["logs"]' is not assignable to parameter of type '["logs", [string]]'.`

The fix is relatively simple and I will submit a pull request shortly.

**Comment by oscartbeaumont** [comment]
Thanks! Should be fixed!
