### ISSUE TITLE
Are the new versions of the `*-query` packages going to be published?

### ISSUE THREAD

**Issue by pauliesnug** [oscartbeaumont/rspc#238]
Hi, currently I'm developing a project in which I would like to use the bleeding edge of rspc, however it isn't possible to use `pnpm` to install from a GitHub workspace, so the only solution is to publish release candidates of all rspc packages, just like how `@rspc/client#1.0.0.rc-3` is published to npm. https://github.com/pnpm/pnpm/issues/4765

**Comment by pauliesnug** [comment]
@oscartbeaumont Hiya, any update on this?

**Comment by Brendonovich** [comment]
This is supposed to happen on each commit, but it looks like that workflow is broken atm. Will be fixed soon.

**Comment by Brendonovich** [comment]
All `@rspc/*` packages should now have latest-commit versions available on the `main` tag

**Comment by pauliesnug** [comment]
Thanks so much! This seems to be working and we've updated the project accordingly.
