### ISSUE TITLE
Support for Axum 0.7

### ISSUE THREAD

**Issue by banool** [oscartbeaumont/rspc#254]
Hey hey, correct me if I'm wrong but I believe this library doesn't support Axum 0.7 right now. It'd be great if it did. I see httpz also only supports Axum 0.6, and I can't see a PR currently updating it to 0.7. In fact httpz seems to be archived, so I'm not sure how it'll be possible to update rspc to support Axum 0.7. Any ideas on the best approach? Happy to help out.

**Comment by WuGGu** [comment]
Hi, @banool is right. httpz is archived. @oscartbeaumont Is this the end of this project and a perspective to support axum 0.7? Realy digging right now into the tRPC stuff and would love to add this to my axum project insead of classical REST calls.

**Comment by oscartbeaumont** [comment]
We will be supporting Axum 0.7 just without `httpz`. I think `httpz` is cool but I don't think it's really achieving it's goal so I think moving the adapters directly into rspc will make a better experience for everyone.

Hopefully going to be working on this issue this weekend cause it's very overdue.

**Comment by oscartbeaumont** [comment]
I apologise for this taking so long.

You will need to refer to the release notes [here](https://github.com/oscartbeaumont/rspc/releases/tag/v0.1.4) for how to upgrade.
