### ISSUE TITLE
Docs refer to middleware support that doesn't exist

### ISSUE THREAD

**Issue by banool** [oscartbeaumont/rspc#256]
The docs here refer to a `.middleware` function on Router: https://www.rspc.dev/server/middleware. There is no such function in the latest version (1.0.0-rc.5).

**Comment by oscartbeaumont** [comment]
All of the main docs are for 0.1.3 so they will be incorrect (there is a link to the beta docs at the top but the beta docs are pretty empty). Once the stable release is out the docs will be updated.

**Comment by oscartbeaumont** [comment]
I'm going to close this. Will hopefully release docs for 1.0.0-rc.x very soon.
