### ISSUE TITLE
Confusion around @rspc/react and @rspc/react-query

### ISSUE THREAD

**Issue by skycoop** [oscartbeaumont/rspc#286]
The [docs](https://www.rspc.dev/client/react) say to install `@rspc/react-query` but the most recent published version seems to be a commit off of master from 7 months ago and will pull down old versions of the rpsc and react-query packages. Installing `@rspc/react`  seems to get v0.2 of rspc and the query client and a modern version of react-query. Do the docs need updated or does `@rspc/react-query` need to be updated?

**Comment by oscartbeaumont** [comment]
The plan is to migrate from `@rspc/react` to `@rspc/react-query` in the future.

`@rspc/react-query` has no stable releases, they are all nightlies published from specific git commits.

You should use `@rspc/react` for now, sorry for the confusion I will update the docs.

**Comment by oscartbeaumont** [comment]
Okay have published the latest clients with `@rspc/*-query` and put a deprecation notice on the `@rspc/react` and `@rspc/solid`.
