### ISSUE TITLE
@rspc/react MJS build isn't stripping out type-only exports

### ISSUE THREAD

**Issue by jedwards1211** [oscartbeaumont/rspc#291]
```
File: javascript/esm|/Users/andy/gh/battalion-webapp/frontend/node_modules/.pnpm/@rspc+react@0.2.1_@tanstack+react-query@5.50.1_react@18.3.1/node_modules/@rspc/react/dist/index.mjs:1:1
  × HarmonyLinkingError: export 'BaseOptions' (reexported as 'BaseOptions') was not found in '@rspc/query-core' (possible exports: createRSPCQueryUtils)
     ╭─[217:1]
 217 │ }
 218 │ export {
 219 │   BaseOptions2 as BaseOptions,
     ·   ───────────────────────────
 220 │   createReactQueryHooks
 221 │ };
```

**Comment by oscartbeaumont** [comment]
I tried to reproduce this with [Twidge](https://twidge.app) and another independant project and I could not. I am certain this is a problem given enough people have reported it but if you have the time can you make a minimum reproduction it would be great for me to be able to actually test fixes.

**Comment by oscartbeaumont** [comment]
Tagging @johann-crabnebula as I know they hit the same problem.

**Comment by jedwards1211** [comment]
@oscartbeaumont reproducing depends on using a bundler/config that resolves to the .mjs files instead of the .js files.

In any case, using `export type` should fix the problem:
```ts
export type { BaseOptions } from "@rspc/query-core";
```

**Comment by oscartbeaumont** [comment]
Okay this is published as 0.2.2 of the respective packages. Let me know if it fixes the problem!

**Comment by johann-crabnebula** [comment]
Will have a look later today

**Comment by jedwards1211** [comment]
@oscartbeaumont yup it fixed the problem for me!
