### ISSUE TITLE
where are the source repositories for the npm packages?

### ISSUE THREAD

**Issue by jedwards1211** [oscartbeaumont/rspc#292]
I can't seem to figure out where `@rspc/react` etc sources are located.  Otherwise I would help make a PR to fix #291

**Comment by oscartbeaumont** [comment]
It is documented in the README. You can find it on the [v0.x](https://github.com/oscartbeaumont/rspc/tree/v0.x) branch.
<img width="928" alt="Screenshot 2024-07-09 at 2 26 34 PM" src="https://github.com/oscartbeaumont/rspc/assets/21004798/3fe3c2b5-d705-43c6-b555-e38cbd464144">
