### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by oscartbeaumont** [oscartbeaumont/rspc#55]
Using [criterion](https://docs.rs/criterion/latest/criterion/) add a bunch of benchmarks into the repository and setup a CI workflow to track changes over time.

**Comment by epompeii** [comment]
@oscartbeaumont do you want to track the results of these benchmarks?

If so, I've built an adapter for `criterion` in my continuous benchmarking tool, Bencher: https://github.com/bencherdev/bencher
I would be more than happy open a PR to start tracking`rspc` benchmark results.

**Comment by oscartbeaumont** [comment]
I would be open to accepting a PR as long as it's free for me.
