### ISSUE TITLE
VS Code Extension incompatible with the current version

### ISSUE THREAD

**Issue by Nivek92** [oscartbeaumont/rspc#82]
Hey just just want to let you know, I tried to install the extension, unfortunately I receive the following error.

`Can't install 'oscartbeaumont.rspc-vscode' extension because it is not compatible with the current version of Visual Studio Code (version 1.67.2).`

**Comment by oscartbeaumont** [comment]
I am running Vscode `Version: 1.73.1` with the extension and it is working fine. When initialising the plugin the manfiest defaulted to supporting version `1.70.0` and up. Try upgrading Vscode and installing again!
