### ISSUE TITLE
generate ts types with type keyword instead of interface

### ISSUE THREAD

**Issue by kkharji** [oscartbeaumont/rspc#83]
Hello,

It came to my attention while trying to use an awesome library for forms that `interface` might have some limitation for developers using typescript advance type system.

It would be awesome if there is an option to generate with `type` keyword instead of `interface` keyword.

Thanks 

See: https://github.com/fabian-hiller/modular-forms/issues/2

**Comment by Brendonovich** [comment]
We're going to go ahead with this change in Specta, since the only real advantages provided by interfaces are declaration merging and compatibility with classes, neither of which are of concern to Specta or rspc.

**Comment by kkharji** [comment]
Great to hear. Thanks @Brendonovich

**Comment by oscartbeaumont** [comment]
Sorry, completely forgot to reply.

It makes sense to go ahead with the change to types. I have had enough people who know way more Typescript than me, agree making this change is fine. For reference [this](https://www.youtube.com/watch?v=zM9UPcIyyhQ) recent video by Matt Pocock brings up what is essentially the problem we have here.
